---
name: QATLibrary CI
on: push

jobs:
  build-n-publish:
    name: Build, test and publish QATLibrary ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
   
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
   
    - name: Install built wheel file
      run: |
        pip install dist/$(ls dist | grep -i .whl)
        qat --version

    - name: Init QAT Sample Files
      run: |
        qat init

    - name: Run QATLibrary CLI Tests
      run: |
        qat run -f TestCases.csv -c config.yaml -rc

    - name: Twine check dist
      run: |
        twine check dist/*

    - name: Publish QATLibrary ðŸ“¦ to Test PyPI
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}    
      run: |
        twine upload dist/*

    - name: Publish QATLibrary ðŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}    
      run: |
        twine upload dist/*

